const express = require("express");
const userRoutes = require("./users");
const tokenRoutes = require("./token");
const postRoutes = require("./post.route");
const commentRoutes = require("./comment.route");
const groupRoutes = require("./group.route");
const groupPostRoutes = require("./group_post.route");
const friendRoutes = require("./friend.route");
// const notificationRoutes = require("./notification.route");
// const userSettingRoutes = require("./user_setting.route");
const notificationRoutes = require("./notification.route");
const channelRoutes = require("./channel.route");
const mediaRoutes = require("./media.route");
const agoraRoutes = require("./agora.route");
const adsRoutes = require("./ads.route");
const paymentRoutes = require("./payment.route");
const storyRoutes = require("./story.route");
const adminRoutes = require("./admin.route");
const router = express.Router();

router.get("/", (req, res) => {
  res.send("Welcome To Final Assignment!");
});

router.use("/user", userRoutes);
router.use("/refresh", tokenRoutes);
router.use("/post", postRoutes);
router.use("/comment", commentRoutes);
router.use("/group", groupRoutes);
router.use("/group-post", groupPostRoutes);
router.use("/", friendRoutes);
router.use("/notifications", notificationRoutes);
router.use("/channels", channelRoutes);
router.use("/media", mediaRoutes);
router.use("/agora", agoraRoutes);
router.use("/ads", adsRoutes);
router.use("/payment", paymentRoutes);
router.use("/stories", storyRoutes);
router.use("/admin", adminRoutes);
module.exports = router;
